### ISSUE TITLE
camera and hand tracking issues

### ISSUE THREAD

**Issue by leftlinker** [calebcram/Passthrough-Online-MRTK_Quest---Sample#1]
when building with the exact same version of unity as you used I am running into two issues.
after launch the camera is stuck and it feel like tracking is not working at all - fixed that by changing some things in the camera settings of the MRTK toolkit. 

another issue I could not resolve is hand tracking not working on quest 2 - if I set the input to Passthrough the camera is stuck again any advice?

**Comment by calebcram** [comment]
Apologies for the delay on this! Ahhh this is a common issue. What's happening is MRTK/Unity is essentially decoupling from Oculus. While annoying, there is an easy solution. Let me know how this ends up working out for you. These steps should fix both of your described issues allowing you to build and sideload your apk to a Quest HMD. Keep in mind this happens very frequently due to re-importing when opening and closing 

1.) Open the project with the original camera and input settings as they were setup. 
2.) At the top of the unity window, follow menu path:
         - Mixed Reality Toolkit > Utilities > Oculus > Integrate Oculus Integration Unity Modules
         - Image of this attached below.
3.) The above step should integrate Oculus Integration with Unity and MRTK allowing MRTK interactions to function on the Quest1&2 when deployed via the android platform. 


![image](https://user-images.githubusercontent.com/49875750/200926136-eaf0be63-8b76-4173-9b8c-526c55834117.png)

**Comment by calebcram** [comment]
I'm going to close this issue for now, but if you have any other questions or issues, please don't hesitate to re-open this issue, or create a new one!
